export const THEMES = [
  { name: "light", label: "Light", colors: ["#ffffff", "#f2f2f2", "#000000"] },
  { name: "dark", label: "Dark", colors: ["#1d232a", "#191e24", "#a6adbb"] },
  { name: "cupcake", label: "Cupcake", colors: ["#faf7f5", "#efeae6", "#65c3c8"] },
  { name: "bumblebee", label: "Bumblebee", colors: ["#ffffff", "#f2f2f2", "#e0a82e"] },
  { name: "emerald", label: "Emerald", colors: ["#ffffff", "#f2f2f2", "#66cc8a"] },
  { name: "corporate", label: "Corporate", colors: ["#ffffff", "#f2f2f2", "#4b6bfb"] },
  { name: "synthwave", label: "Synthwave", colors: ["#2d1b69", "#221551", "#f92ef7"] },
  { name: "retro", label: "Retro", colors: ["#ece3ca", "#e4d8b4", "#ef9995"] },
  { name: "cyberpunk", label: "Cyberpunk", colors: ["#ffee00", "#e6cb00", "#ff7598"] },
  { name: "valentine", label: "Valentine", colors: ["#fae7e9", "#f1d2d6", "#e96d7b"] },
  { name: "halloween", label: "Halloween", colors: ["#212121", "#1a1a1a", "#f87272"] },
  { name: "garden", label: "Garden", colors: ["#e9e7e7", "#dfdbdb", "#5c7f67"] },
  { name: "forest", label: "Forest", colors: ["#171212", "#120e0e", "#1eb854"] },
  { name: "aqua", label: "Aqua", colors: ["#345da7", "#2b4d8c", "#09ecf3"] },
  { name: "lofi", label: "Lofi", colors: ["#ffffff", "#f2f2f2", "#000000"] },
  { name: "pastel", label: "Pastel", colors: ["#ffffff", "#f2f2f2", "#d1c1d7"] },
  { name: "fantasy", label: "Fantasy", colors: ["#ffffff", "#f2f2f2", "#6e0b70"] },
  { name: "wireframe", label: "Wireframe", colors: ["#ffffff", "#f2f2f2", "#b8b8b8"] },
  { name: "black", label: "Black", colors: ["#000000", "#000000", "#ffffff"] },
  { name: "luxury", label: "Luxury", colors: ["#09090b", "#020203", "#ffffff"] },
  { name: "dracula", label: "Dracula", colors: ["#282a36", "#21222c", "#ff79c6"] },
  { name: "cmyk", label: "Cmyk", colors: ["#ffffff", "#f2f2f2", "#4506cb"] },
  { name: "autumn", label: "Autumn", colors: ["#f1f1f1", "#e7e7e7", "#8c0327"] },
  { name: "business", label: "Business", colors: ["#202020", "#191919", "#1c4f82"] },
  { name: "acid", label: "Acid", colors: ["#fafafa", "#f1f1f1", "#ff00ff"] },
  { name: "lemonade", label: "Lemonade", colors: ["#fafff5", "#f1facc", "#519903"] },
  { name: "night", label: "Night", colors: ["#0f172a", "#090e1a", "#38bdf8"] },
  { name: "coffee", label: "Coffee", colors: ["#20161f", "#171017", "#127c71"] },
  { name: "winter", label: "Winter", colors: ["#ffffff", "#f2f2f2", "#047aff"] },
  { name: "dim", label: "Dim", colors: ["#2a303c", "#242933", "#1fb2a6"] },
  { name: "nord", label: "Nord", colors: ["#eceff4", "#e5e9f0", "#5e81ac"] },
  { name: "sunset", label: "Sunset", colors: ["#121c22", "#0c1216", "#ff865b"] },
];

export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Korean",
  "Hindi",
  "Russian",
  "Portuguese",
  "Arabic",
  "Italian",
  "Turkish",
  "Dutch",
];

export const LANGUAGE_TO_FLAG = {
  english: "gb",
  spanish: "es",
  french: "fr",
  german: "de",
  mandarin: "cn",
  japanese: "jp",
  korean: "kr",
  hindi: "in",
  russian: "ru",
  portuguese: "pt",
  arabic: "sa",
  italian: "it",
  turkish: "tr",
  dutch: "nl",
};